vim.opt.termguicolors = true
require("packer-setup.packer")
--require("artem-packer-setup.set")
require("packer-setup.after.plugin.telescope")
require("packer-setup.after.plugin.treesitter")
require("packer-setup.after.plugin.harpoon")
require("packer-setup.after.plugin.undotree")
require("packer-setup.after.plugin.fugitive")
require("packer-setup.after.plugin.lsp")
--require("artem-packer-setup.remap")
require("packer-setup.after.plugin.copilot")
require("packer-setup.after.plugin.magma")
require("packer-setup.after.plugin.comment")
require("packer-setup.after.plugin.colorscheme")

