vim.opt.termguicolors = true
require("artem-packer.after.plugin.colorscheme")
require("artem-packer.packer")
require("artem-packer.set")
require("artem-packer.after.plugin.telescope")
require("artem-packer.after.plugin.treesitter")
require("artem-packer.after.plugin.harpoon")
require("artem-packer.after.plugin.undotree")
require("artem-packer.after.plugin.fugitive")
require("artem-packer.after.plugin.lsp")
require("artem-packer.remap")
require("artem-packer.after.plugin.copilot")
require("artem-packer.after.plugin.magma")
require("artem-packer.after.plugin.comment")

